#---
#- name: Update Nodal Configuration (using gNMI SET)
#  gnmi_config:
#    update:
#      - path: /
#        val: '{{ config }}'
#  vars:
#    config: "{{ lookup('file', playbook_dir + '/../build/' + inventory_hostname_short + '/config.json') | from_json }}"
#  register: testout
#- name: dump test output
#  debug:
#    msg: '{{ testout.output }}'    
#
---

- name: dump ansible_connection
  debug:
    msg: 'template: src=../templates/interface.cfg.j2 dest={{playbook_dir}}/configs/{{hostname}}/interfaces.json'

- name: generate ip interface configs from templates
  #template: src=../templates/interface.cfg.j2 dest=configs/{{hostname}}/interfaces.json
  template: src=../templates/interface.cfg.j2 dest={{playbook_dir}}/configs/{{hostname}}/interfaces.json
