---
- name: Get Configuration using gNMI
  gather_facts: false
  hosts: nokia

  collections:
  - nokia.grpc

  tasks:

  - name: Get Full Nodal Configuration (using gNMI GET)
    gnmi_get:
      type: CONFIG
      path:
        - /
    register: testout

  - name: dump test output
    debug:
      msg: '{{ testout.output }}'
