---
- name: gNMI Subscribe ONCE
  gather_facts: false
  hosts: nokia

  collections:
  - nokia.grpc

  tasks:
  - name: Get Nodal Configuration (using gNMI Subscribe/ONCE)
    gnmi_subscribe:
      mode: ONCE #STREAM is also possible
      subscription:
        - path: /system/name/host-name
        #- path: /platform/control[slot=*]/software-version
    register: testout

  - name: dump test output
    debug:
      msg: '{{ testout.output }}'
